services:
  bot:
    container_name: requina-bot
    build:
      context: .
      dockerfile: Dockerfile
    image: requina-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - CHATGPT_TOKEN=$CHATGPT_TOKEN
